# Import Library & Membaca Data

In [ ]:
import pandas as pd

In [ ]:
hist = pd.read_csv('history.csv')
players = pd.read_csv('players.csv')
pg = pd.read_csv('purchased_games.csv')
achiev = pd.read_csv('achievements.csv')

Hist : itu dataset History, yang isinya history penghargaan yang diperoleh pemain

Players : itu dataset Players pada folder Playstation

Pg : itu dataset purchased games, yang isinya itu daftar game yang dibeli pemain

Achiev : itu dataset achievement pemain

Observasi yang digunakan : Playerid

# Informasi File Dataset

In [ ]:
hist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19510083 entries, 0 to 19510082
Data columns (total 3 columns):
 #   Column         Dtype
---  ------         -----
 0   playerid       int64
 1   achievementid  object
 2   date_acquired  object
dtypes: int64(1), object(2)
memory usage: 446.6+ MB

In [ ]:
hist

          playerid   achievementid        date_acquired
0          1911732  670209_5436079  2024-11-28 10:23:24
1          1911732  670209_5436078  2024-11-28 09:36:41
2          1911732  670209_5436077  2024-11-28 08:31:54
3          1911732  670209_5436076  2024-11-28 08:19:23
4          1911732  658551_5368954  2024-10-05 13:12:35
...            ...             ...                  ...
19510078    301920          73_769  2010-03-21 02:34:00
19510079    301920         73_2253  2010-03-21 02:17:12
19510080    301920          73_767  2010-03-21 01:48:49
19510081    301920          73_768  2010-03-20 21:41:10
19510082    301920          73_757  2010-03-20 16:19:38

[19510083 rows x 3 columns]

In [ ]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356600 entries, 0 to 356599
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   playerid  356600 non-null  int64
 1   nickname  356600 non-null  object
 2   country   356600 non-null  object
dtypes: int64(1), object(2)
memory usage: 8.2+ MB

In [ ]:
players

        playerid         nickname             country
0        2744567  ieizazuBisnorog             Croatia
1         328452     DiscoGitaroo       United States
2        2521482          Ectivey      United Kingdom
3         390175      Tomie_Again  Korea, Republic of
4        4348945     Lordhell1986  Russian Federation
...          ...              ...                 ...
356595    133971             ciot       United States
356596    138255      Galactus999       United States
356597    138787  zZRoNBurgundyZz       United States
356598    138858       Diablofans               Japan
356599    140656  xSniper_Te0RiaL              France

[356600 rows x 3 columns]

In [ ]:
pg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46582 entries, 0 to 46581
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   playerid  46582 non-null  int64
 1   library   46582 non-null  object
dtypes: int64(1), object(1)
memory usage: 728.0+ KB

In [ ]:
pg

       playerid                                            library
0        268071  [14972, 417905, 14693, 7742, 20162, 461983, 12...
1       2218485  [410618, 17456, 16034, 138931, 175202, 331007,...
2        253885  [417808, 706747, 619583, 492711, 555631, 18167...
3       1911732  [670209, 694794, 658551, 582894, 602666, 65531...
4       3098524  [19362, 170350, 12653, 20230, 12750, 18141, 41...
...         ...                                                ...
46577   3753984  [18141, 9459, 7779, 619584, 14339, 544742, 202...
46578   1739644  [141933, 333860, 8600, 20795, 7248, 167482, 44...
46579    415935  [550305, 417785, 420539, 417808, 550307, 14901...
46580    210838  [167482, 193795, 9020, 407954, 420948, 21135, ...
46581    308899  [456006, 386922, 372449, 145680, 139929, 14567...

[46582 rows x 2 columns]

In [ ]:
achiev.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 846563 entries, 0 to 846562
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   achievementid  846563 non-null  object
 1   gameid         846563 non-null  int64
 2   title          846559 non-null  object
 3   description    846547 non-null  object
 4   rarity         846563 non-null  object
dtypes: int64(1), object(4)
memory usage: 32.3+ MB

In [ ]:
achiev

,achievementid,gameid,title,description,rarity
0,749980_6103480,749980,Platinum Cup,Get all the trophies,Platinum
1,749980_6103481,749980,Arcade Beginner,Finish race,Bronze
2,749980_6103482,749980,Arcade Beginner Dirt,Finish race,Bronze
3,749980_6103483,749980,Arcade Intermediate,Finish race,Silver
4,749980_6103484,749980,Arcade Advanced,Finish race,Silver
...,...,...,...,...,...
846558,439093_6141713,439093,Are you there?,Complete the Shelter DLC,Silver
846559,439093_6141714,439093,I Can do This All Day,Sell each dish at least once,Bronze
846560,439093_6141715,439093,Bar Brawl,Hunt the mutant by throwing a bottle at him,Bronze
846561,439093_6141716,439093,It Stings,Sell 50 dishes that require a skewer in the re...,Bronze
846562,439093_6141717,439093,Gear Up,Fully upgrade the weapon,Bronze

# Pengecekan Duplikasi

In [ ]:
hist.duplicated().sum()

np.int64(0)

In [ ]:
players.duplicated().sum()

np.int64(0)

In [ ]:
pg.duplicated().sum()

np.int64(0)

In [ ]:
achiev.duplicated().sum()

np.int64(0)

# Penggabungan Dataset

### Menggabungkan history + achievement terlebih dahulu
Dilakukan penggabungan ini karena dataset achievement tidak memiliki variabel playerid. Digabungkan dengan dataset history karena kedua dataset ini berhubungan satu sama lain.

In [ ]:
hist_merge = hist.merge(achiev, on='achievementid', how='left')
hist_merge

,playerid,achievementid,date_acquired,gameid,title,description,rarity
0,1911732,670209_5436079,2024-11-28 10:23:24,670209,Gigas,Defeated Gigas.,Bronze
1,1911732,670209_5436078,2024-11-28 09:36:41,670209,Corrupter,Defeated Corrupter.,Bronze
2,1911732,670209_5436077,2024-11-28 08:31:54,670209,Abaddon,Defeated Abaddon.,Bronze
3,1911732,670209_5436076,2024-11-28 08:19:23,670209,Camp Preparation,Activated the first Camp.,Bronze
4,1911732,658551_5368954,2024-10-05 13:12:35,658551,Pure Speed,Have a runner score from first without the bas...,Silver
...,...,...,...,...,...,...,...
19510078,301920,73_769,2010-03-21 02:34:00,73,Bare-knuckle Slugger,Defeat 50 enemies with hand-to-hand combat,Silver
19510079,301920,73_2253,2010-03-21 02:17:12,73,Survivor,Defeat 75 enemies in a row without dying,Silver
19510080,301920,73_767,2010-03-21 01:48:49,73,Triple Dyno-Might!,Defeat three enemies with one explosion,Bronze
19510081,301920,73_768,2010-03-20 21:41:10,73,Bare-knuckle Brawler,Defeat 20 enemies with hand-to-hand combat,Bronze
19510082,301920,73_757,2010-03-20 16:19:38,73,First Treasure,Find one treasure,Bronze

### Agregasi ke level player, karena fokus analisis adalah analisis player. Dan itulah alasan variabel title dan description tidak digunakan karena kedua variabel tersebut tidak berkaitan dengan analisis players tetapi berkaitan dengan analisis games.

In [ ]:
df_hist = hist_merge.groupby('playerid').agg({
    'achievementid': 'count',
    'gameid': 'nunique',
    'rarity': 'nunique'
}).reset_index()

df_hist.rename(columns={
    'achievementid': 'total_achievement',
    'gameid': 'total_game_from_achievement',
    'rarity': 'variasi_rarity'
}, inplace=True)

df_hist

      playerid  total_achievement  total_game_from_achievement  variasi_rarity
0           77               2272                          165               3
1          145               4360                          146               4
2          276                771                           56               4
3          453               1032                           49               4
4          904               3050                          171               4
...        ...                ...                          ...             ...
4995   4741908              12561                          939               4
4996   4742277              10649                          404               4
4997   4743530               1845                          180               3
4998   4743886                442                           33               3
4999   4745795               1554                           84               4

[5000 rows x 4 columns]

In [ ]:
df_hist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   playerid                     5000 non-null   int64
 1   total_achievement            5000 non-null   int64
 2   total_game_from_achievement  5000 non-null   int64
 3   variasi_rarity               5000 non-null   int64
dtypes: int64(4)
memory usage: 156.4 KB

# Penggabungan Dataset

In [ ]:
df1 = pd.merge(players, pg, on='playerid', how='left')
df1

,playerid,nickname,country,library
0,2744567,ieizazuBisnorog,Croatia,NaN
1,328452,DiscoGitaroo,United States,NaN
2,2521482,Ectivey,United Kingdom,NaN
3,390175,Tomie_Again,"Korea, Republic of",NaN
4,4348945,Lordhell1986,Russian Federation,"[707721, 751920, 146, 666513, 182258, 669819, ..."
...,...,...,...,...
356595,133971,ciot,United States,NaN
356596,138255,Galactus999,United States,NaN
356597,138787,zZRoNBurgundyZz,United States,NaN
356598,138858,Diablofans,Japan,NaN
356599,140656,xSniper_Te0RiaL,France,NaN

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356600 entries, 0 to 356599
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   playerid  356600 non-null  int64
 1   nickname  356600 non-null  object
 2   country   356600 non-null  object
 3   library   46582 non-null   object
dtypes: int64(1), object(3)
memory usage: 10.9+ MB

In [ ]:
df_final = pd.merge(df1, df_hist, on='playerid', how='left')
df_final

,playerid,nickname,country,library,total_achievement,total_game_from_achievement,variasi_rarity
0,2744567,ieizazuBisnorog,Croatia,NaN,NaN,NaN,NaN
1,328452,DiscoGitaroo,United States,NaN,NaN,NaN,NaN
2,2521482,Ectivey,United Kingdom,NaN,NaN,NaN,NaN
3,390175,Tomie_Again,"Korea, Republic of",NaN,NaN,NaN,NaN
4,4348945,Lordhell1986,Russian Federation,"[707721, 751920, 146, 666513, 182258, 669819, ...",NaN,NaN,NaN
...,...,...,...,...,...,...,...
356595,133971,ciot,United States,NaN,NaN,NaN,NaN
356596,138255,Galactus999,United States,NaN,NaN,NaN,NaN
356597,138787,zZRoNBurgundyZz,United States,NaN,NaN,NaN,NaN
356598,138858,Diablofans,Japan,NaN,NaN,NaN,NaN
356599,140656,xSniper_Te0RiaL,France,NaN,NaN,NaN,NaN

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356600 entries, 0 to 356599
Data columns (total 7 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   playerid                     356600 non-null  int64
 1   nickname                     356600 non-null  object
 2   country                      356600 non-null  object
 3   library                      46582 non-null   object
 4   total_achievement            5000 non-null    float64
 5   total_game_from_achievement  5000 non-null    float64
 6   variasi_rarity               5000 non-null    float64
dtypes: float64(3), int64(1), object(3)
memory usage: 19.0+ MB

# Penanganan Missing Values

In [ ]:
df_final['total_achievement'] = df_final['total_achievement'].fillna(0)

In [ ]:
df_final['library'] = df_final['library'].fillna('No Games')
df_final['total_game_from_achievement'] = df_final['total_game_from_achievement'].fillna('No Achievement')
df_final['variasi_rarity'] = df_final['variasi_rarity'].fillna('No Achievement')

In [ ]:
df_final

,playerid,nickname,country,library,total_achievement,total_game_from_achievement,variasi_rarity
0,2744567,ieizazuBisnorog,Croatia,No Games,0.0,No Achievement,No Achievement
1,328452,DiscoGitaroo,United States,No Games,0.0,No Achievement,No Achievement
2,2521482,Ectivey,United Kingdom,No Games,0.0,No Achievement,No Achievement
3,390175,Tomie_Again,"Korea, Republic of",No Games,0.0,No Achievement,No Achievement
4,4348945,Lordhell1986,Russian Federation,"[707721, 751920, 146, 666513, 182258, 669819, ...",0.0,No Achievement,No Achievement
...,...,...,...,...,...,...,...
356595,133971,ciot,United States,No Games,0.0,No Achievement,No Achievement
356596,138255,Galactus999,United States,No Games,0.0,No Achievement,No Achievement
356597,138787,zZRoNBurgundyZz,United States,No Games,0.0,No Achievement,No Achievement
356598,138858,Diablofans,Japan,No Games,0.0,No Achievement,No Achievement
356599,140656,xSniper_Te0RiaL,France,No Games,0.0,No Achievement,No Achievement

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 356600 entries, 0 to 356599
Data columns (total 7 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   playerid                     356600 non-null  int64
 1   nickname                     356600 non-null  object
 2   country                      356600 non-null  object
 3   library                      356600 non-null  object
 4   total_achievement            356600 non-null  float64
 5   total_game_from_achievement  356600 non-null  object
 6   variasi_rarity               356600 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 19.0+ MB

In [ ]:
df_final.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
356595    False
356596    False
356597    False
356598    False
356599    False
Length: 356600, dtype: bool

In [ ]:
df_final.duplicated().sum()

np.int64(0)